[[main]]
name = "Services"
identifier = "services"
weight = 1

[main.params]
section = "services"

[[main]]
name = "Pathways"
identifier = "pathways"
weight = 2

[main.params]
section = "pathways"

[[main]]
name = "Process"
identifier = "process"
weight = 3

[main.params]
section = "process"

[[main]]
name = "FAQ"
identifier = "faq"
weight = 4

[main.params]
section = "faq"

[[main]]
name = "Guides"
identifier = "guides"
weight = 5

[main.params]
page = "/guides/"

[[main]]
name = "Partners"
identifier = "partners"
weight = 6

[main.params]
page = "/partners/"
